version: '3.3'

services:
  async-mcp:
    build: ./server
    container_name: async-mcp
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - MAX_REQUESTS=${MAX_REQUESTS:-3}  # Low for testing
      - WINDOW_MINUTES=${WINDOW_MINUTES:-5}  # Short window for testing
    volumes:
      - ~/async:/results
      - ./logs:/app/logs
    stdin_open: true
    tty: true
    restart: unless-stopped